#!/bin/bash

if [ "$1" = '' ]; then
	echo 'Usage: archrm <path to checkout>'
	exit 1
fi

# FIXME: Check if there are uncommited changes
#pushd $1
#
#popd

rm -rf $1

# vim: set noexpandtab tabstop=8 shiftwidth=8 wrap:textwidth=132 autoindent
# kate: indent-mode normal; indent-width 8; tab-indents on; tab-width 8; word-wrap on; word-wrap-column 132
