#!/bin/bash

scriptname=${0##*/}

if [ "$1" = '' ]; then
	echo 'Usage: '$scriptname' <package name>...'
	exit 1
fi

case $scriptname in
	archco)
		SVNURL="svn+ssh://gerolde.archlinux.org/srv/svn-packages";;
	communityco)
		SVNURL="svn+ssh://aur.archlinux.org/srv/svn-packages";;
	*)
		echo "error: couldn't find svn url for $scriptname"
		exit 1
		;;
esac

for i in "$@"; do
	svn co "$SVNURL/$i"
done
