#!/bin/bash
# TODO make this work for community too

if [ "$1" = "" ]; then
	echo "Usage: archco <package name> [<package name>]"
	exit 1
fi

for i in "$@"; do
     svn co svn+ssh://svn.archlinux.org/srv/svn-packages/$i
done
