#!/bin/bash

if [ "$1" = "" ]; then
    echo "Usage: archrelease <repo>"
    exit 1
fi

if [ ! -f PKGBUILD ]; then
    echo "archrelease: PKGBUILD not found"
    exit 1
fi

if [ "$(basename $(readlink -f .))" != "trunk" ]; then
    echo "archrelease: Not in a package trunk dir"
    exit 1
fi

if [ "$(svn diff)" != "" ]; then
    echo "archrelease: You have not committed your changes yet!"
    echo "             Please run 'upgpkg' or 'svn commit' first"
    exit 1
fi

pushd ..
if [ -d repos/$1 ]; then
    svn rm --force -q repos/$1
    svn commit -q -m "archrelease: remove $1"
fi
svn copy -q -r HEAD trunk repos/$1
svn commit -q -m "archrelease: copy trunk to $1"
popd
