#!/bin/bash

if [ "$1" = '' ]; then
	echo 'Usage: communityco <package name> [<package name>]'
	exit 1
fi

for i in "$@"; do
	svn co svn+ssh://aur.archlinux.org/srv/svn-packages/$i
done

# vim: set noexpandtab tabstop=8 shiftwidth=8 wrap:textwidth=132 autoindent
# kate: indent-mode normal; indent-width 8; tab-indents on; tab-width 8; word-wrap on; word-wrap-column 132
