#!/bin/bash

source /etc/makepkg.conf

cmd=`basename $0`

if [ ! -f PKGBUILD ]; then
	echo "No PKGBUILD file"
	exit 1
fi

source PKGBUILD
pkgfile=${pkgname}-${pkgver}-${pkgrel}.pkg.tar.gz

if [ ! -f $pkgfile ]; then
	echo "File $pkgfile doesn't exist"
	exit 1
fi

if [ "$cmd" == "extrapkg" ]; then
	repo="extra"
	tag="CURRENT"
elif [ "$cmd" == "currentpkg" ]; then
	repo="current"
	tag="CURRENT"
elif [ "$cmd" == "testingpkg" ]; then
	repo="testing"
	tag="TESTING"
elif [ "$cmd" == "unstablepkg" ]; then
	repo="unstable"
	tag="CURRENT"
elif [ "$cmd" == "communitypkg" ]; then
	repo="community"
	tag="CURRENT"
fi

if [ "$repo" != "community" ]; then
	scp $pkgfile archlinux.org:staging/$repo/add
else
	if [ ! -f ~/.tupkg ]; then
	   echo "Must configure tupkg via ~/.tupkg, cancelled"
	   exit 1
	fi
	tupkg $pkgfile
fi
if [ $? -ne 0 ]; then
	echo "Cancelled"
	exit 1
fi
echo "===> Uploaded $pkgfile"

if [ "$1" != "" ]; then
cvs commit -m "upgpkg: $pkgname $pkgver-$pkgrel
$1" > /dev/null
if [ $? -ne 0 ]; then
	echo "Cancelled"
	exit 1
fi
echo "===> Commited with \"upgpkg: $pkgname $pkgver-$pkgrel
$1\" message"
else
cvs commit -m "upgpkg: $pkgname $pkgver-$pkgrel" > /dev/null
if [ $? -ne 0 ]; then
	echo "Cancelled"
	exit 1
fi
echo "===> Commited with \"upgpkg: $pkgname $pkgver-$pkgrel\" message"
fi

cvs tag -c -F -R $tag > /dev/null
if [ $? -ne 0 ]; then
	echo "Cancelled"
	exit 1
fi
echo "===> Tagged as $tag"
