#!/bin/bash
#
# finddeps - find packages that depend on a given depname
#

if [ "$1" = "" ]; then
    echo "usage: finddeps <depname>"
    echo ""
    echo "Find packages that depend on a given depname."
    echo "Run this script from the top-level directory of your ABS tree."
    echo ""
    exit 0
fi

match=$1
tld=$(pwd)

for d in $(find . -type d); do
    cd $d
    if [ -f PKGBUILD ]; then
        unset pkgname depends makedepends
        . PKGBUILD
        for dep in "${depends[@]}"; do
            # lose the version comaparator, if any
            depname=${dep%%[<>=]*}
            if [ "$depname" = "$match" ]; then
                echo "$d (depends)"
            fi
        done
        for dep in "${makedepends[@]}"; do
            # lose the version comaparator, if any
            depname=${dep%%[<>=]*}
            if [ "$depname" = "$match" ]; then
                echo "$d (makedepends)"
            fi
        done
    fi
    cd $tld
done

# vim:ft=sh:ts=4:sw=4:et:
