devtools(7)
===========

Name
----
devtools - Developer tools for the Arch Linux distribution

Description
-----------

Devtools contains tools for package maintenance in Arch Linux. It comes with a
unified command-line frontend called 'pkgctl' that aids to conveniently
interact with all the different tools this collection provides.

The toolset varies from tools for building packages in a clean chroot
('mkarchroot', 'archbuild', ...), packaging related tools ('sogrep', 'diffpkg',
'lddd') and tools for repository management such as ('pkgrepo').

Programs
--------
The list below gives a short overview; see the respective documentation
for details.

pkgctl(1)
	Unified command-line frontend for devtools

archbuild(1)
	Build an Arch Linux package inside a clean chroot

arch-nspawn(1)
	Run a command or OS in a light-weight namespace container

checkpkg(1)
	Compare the current build package with the repository version

diffpkg(1)
	Compare package files using different modes

export-pkgbuild-keys(1)
	Export valid source signing keys from a PKGBUILD

find-libdeps(1)
	Find soname dependencies for a package

find-libprovides(1)
	Find soname's which are provided by a package

lddd(1)
	Find broken library links on your system

mkarchroot(1)
	Creates an arch chroot in a specified location with a specified set of
	packages

makechrootpkg(1)
	Build a PKGBUILD in a given chroot environment

makerepropkg(1)
	Rebuild a package to see if it is reproducible

offload-build(1)
	Build a PKGBUILD on a remote server using makechrootpkg

sogrep(1)
	Find packages using a linked to a given shared library

include::include/footer.asciidoc[]
