# This script was automatically generated by pkgctl
# This function starts pkgctl and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
function pkgctl {
    local cmd cmd_file code
	cmd_file=$(mktemp --tmpdir "pkgctl.outcmd.XXXXXXXXXX")

    if PKGCTL_OUTCMD="${cmd_file}" command pkgctl "$@"; then
        cmd=$(<"$cmd_file")
        command rm -f "$cmd_file"
        eval "$cmd"
    else
        code=$?
        command rm -f "$cmd_file"
        return "$code"
    fi
}

#\builtin alias pkgctl=__pkgctl
#\compdef __pkgctl=pkgctl

# =============================================================================
#
# To initialize pkgctl, add this to your configuration (usually ~/.zshrc):
#
# eval "$(pkgctl init zsh)"
