on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm m4 make openssh subversion rsync arch-install-scripts git bzr mercurial diffutils asciidoc shellcheck
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
           make PREFIX=/usr
           make PREFIX=/usr DESTDIR="$(mktemp -d)" install
           make check || true
           SHELLCHECK_OPTS="-S error" make check
